language: node_js

node_js:
  - "node"

script: bash .travis/build.sh

deploy:
  - provider: pages
    local-dir: dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: staging

  - provider: script
    script: bash .travis/deploy-production.sh
    skip-cleanup: true
    on:
      branch: master

